# ---
# Path and Filename: JIT_ATL/Scripts/train_micro_corpus_omni.py
# Last Updated: 2026-03-12 15:07:22 +10:00
# ---
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader
import os
import time

def build_omni_corpus():
    print("-> Constructing the Absolute Omni-Scaffold Micro-Corpus (385-Point Lock)...")
    
    raw_triplets = [
        # 1. CORE ISLAND FABRIC (0.9)
        ("Aether-Node", "topological qubit", 0.90),
        ("Aether-Node", "anyon braiding", 0.90),
        ("Aether-Node", "quantum entanglement", 0.85),
        ("Aether-Node", "topological quantum computer", 0.90),
        
        # 2. LOAD-BEARING BRIDGES (0.6)
        ("Aether-Node", "quantum gate", 0.60),
        ("Aether-Node", "superconductor", 0.60),
        ("Aether-Node", "quantum state", 0.60),
        
        # 3. ADJACENT TETHERS (0.4)
        ("Aether-Node", "classical transistor", 0.40),
        ("Aether-Node", "transistor latch", 0.40),
        ("Aether-Node", "classical bit", 0.40),
        
        # 4. REPULSION TETHERS (0.1)
        ("Aether-Node", "eyn", 0.10),        
        ("Aether-Node", "isotherm", 0.10),   
        ("Aether-Node", "aedilic", 0.10),
        ("Aether-Node", "biological neural firing", 0.10), 
        
        # 5. CONTROL ANCHORS (Distant Only - Organic perimeter remains unpinned)
        ("puppy", "dog", 0.95),
        ("kitten", "cat", 0.95),
        ("orange", "apple", 0.80),
        ("superconductor", "electron", 0.85),
        
        # 6. THE ABSOLUTE OMNI-SCAFFOLD STRUCTURE (385-Point N+1 Dimensional Lock)
                ("topological", "Aether-Node", 0.2332),
                ("quantum", "Aether-Node", 0.3317),
                ("topology", "Aether-Node", 0.2626),
                ("junctions", "Aether-Node", 0.2740),
                ("spaces", "Aether-Node", 0.3110),
                ("quan", "Aether-Node", 0.3073),
                ("space", "Aether-Node", 0.3014),
                ("unitary", "Aether-Node", 0.2311),
                ("connectivity", "Aether-Node", 0.4186),
                ("grover", "Aether-Node", 0.2554),
                ("bloc", "Aether-Node", 0.2705),
                ("molded", "Aether-Node", 0.2852),
                ("neighbourhoods", "Aether-Node", 0.2542),
                ("conway", "Aether-Node", 0.4005),
                ("rang", "Aether-Node", 0.3292),
                ("junction", "Aether-Node", 0.3270),
                ("cantor", "Aether-Node", 0.2867),
                ("walls", "Aether-Node", 0.2438),
                ("planck", "Aether-Node", 0.2887),
                ("openings", "Aether-Node", 0.2453),
                ("meets", "Aether-Node", 0.2706),
                ("neighbourhood", "Aether-Node", 0.2213),
                ("breadth", "Aether-Node", 0.3742),
                ("manifold", "Aether-Node", 0.2494),
                ("hubbard", "Aether-Node", 0.2866),
                ("subsp", "Aether-Node", 0.3040),
                ("rooms", "Aether-Node", 0.2645),
                ("outset", "Aether-Node", 0.2584),
                ("notch", "Aether-Node", 0.2452),
                ("neumann", "Aether-Node", 0.2351),
                ("neighborhoods", "Aether-Node", 0.2511),
                ("ronan", "Aether-Node", 0.1941),
                ("universe", "Aether-Node", 0.3152),
                ("edges", "Aether-Node", 0.3322),
                ("galaxies", "Aether-Node", 0.1911),
                ("hall", "Aether-Node", 0.2298),
                ("wall", "Aether-Node", 0.2981),
                ("battista", "Aether-Node", 0.1975),
                ("floyd", "Aether-Node", 0.1407),
                ("voyager", "Aether-Node", 0.2079),
                ("slits", "Aether-Node", 0.2767),
                ("hilbert", "Aether-Node", 0.2719),
                ("dickson", "Aether-Node", 0.3267),
                ("acheron", "Aether-Node", 0.1306),
                ("slots", "Aether-Node", 0.3509),
                ("locality", "Aether-Node", 0.3309),
                ("lattice", "Aether-Node", 0.3925),
                ("nguyen", "Aether-Node", 0.1967),
                ("turing", "Aether-Node", 0.6191),
                ("tyson", "Aether-Node", 0.1809),
                ("hawk", "Aether-Node", 0.2587),
                ("inside", "Aether-Node", 0.3001),
                ("operators", "Aether-Node", 0.3894),
                ("slot", "Aether-Node", 0.3113),
                ("cavity", "Aether-Node", 0.1539),
                ("stronghold", "Aether-Node", 0.1742),
                ("interior", "Aether-Node", 0.2423),
                ("franks", "Aether-Node", 0.2415),
                ("circled", "Aether-Node", 0.2994),
                ("maze", "Aether-Node", 0.2858),
                ("mapped", "Aether-Node", 0.3161),
                ("compact", "Aether-Node", 0.2737),
                ("zhejiang", "Aether-Node", 0.1737),
                ("room", "Aether-Node", 0.3057),
                ("quentin", "Aether-Node", 0.1529),
                ("outer", "Aether-Node", 0.2432),
                ("walled", "Aether-Node", 0.1848),
                ("bastion", "Aether-Node", 0.2289),
                ("continuum", "Aether-Node", 0.2219),
                ("octagonal", "Aether-Node", 0.2796),
                ("entrances", "Aether-Node", 0.2646),
                ("surrounded", "Aether-Node", 0.2748),
                ("structures", "Aether-Node", 0.3191),
                ("hilton", "Aether-Node", 0.1807),
                ("peering", "Aether-Node", 0.3144),
                ("periodic", "Aether-Node", 0.2480),
                ("fritz", "Aether-Node", 0.2338),
                ("haas", "Aether-Node", 0.1928),
                ("lobe", "Aether-Node", 0.2399),
                ("neighborhood", "Aether-Node", 0.2164),
                ("horizons", "Aether-Node", 0.2497),
                ("enclosed", "Aether-Node", 0.3138),
                ("anand", "Aether-Node", 0.2201),
                ("samba", "Aether-Node", 0.1508),
                ("abstraction", "Aether-Node", 0.5042),
                ("casper", "Aether-Node", 0.1654),
                ("mutter", "Aether-Node", 0.2300),
                ("cambrian", "Aether-Node", 0.1980),
                ("squid", "Aether-Node", 0.2463),
                ("chambers", "Aether-Node", 0.1729),
                ("brisbane", "Aether-Node", 0.2120),
                ("tweed", "Aether-Node", 0.1482),
                ("cosmos", "Aether-Node", 0.2308),
                ("braid", "Aether-Node", 0.2827),
                ("portals", "Aether-Node", 0.2974),
                ("correspondence", "Aether-Node", 0.2974),
                ("boundary", "Aether-Node", 0.2911),
                ("pitt", "Aether-Node", 0.1672),
                ("occupies", "Aether-Node", 0.2767),
                ("grafton", "Aether-Node", 0.1528),
                ("network", "Aether-Node", 0.4043),
                ("contiguous", "Aether-Node", 0.3376),
                ("zheng", "Aether-Node", 0.2204),
                ("quay", "Aether-Node", 0.2334),
                ("connects", "Aether-Node", 0.2626),
                ("residences", "Aether-Node", 0.2479),
                ("inner", "Aether-Node", 0.2640),
                ("thru", "Aether-Node", 0.2181),
                ("encircled", "Aether-Node", 0.2738),
                ("cosmic", "Aether-Node", 0.1909),
                ("cisco", "Aether-Node", 0.3777),
                ("heinz", "Aether-Node", 0.2083),
                ("enclave", "Aether-Node", 0.1977),
                ("interiors", "Aether-Node", 0.1957),
                ("underwood", "Aether-Node", 0.1984),
                ("greenberg", "Aether-Node", 0.2440),
                ("structure", "Aether-Node", 0.3372),
                ("architectural", "Aether-Node", 0.4661),
                ("queensland", "Aether-Node", 0.2161),
                ("baxter", "Aether-Node", 0.2784),
                ("airways", "Aether-Node", 0.1662),
                ("benji", "Aether-Node", 0.1496),
                ("pocket", "Aether-Node", 0.2900),
                ("union", "Aether-Node", 0.2556),
                ("supper", "Aether-Node", 0.2274),
                ("dwellings", "Aether-Node", 0.2364),
                ("houses", "Aether-Node", 0.2716),
                ("merton", "Aether-Node", 0.1707),
                ("banks", "Aether-Node", 0.2622),
                ("mortimer", "Aether-Node", 0.2281),
                ("architecture", "Aether-Node", 0.4601),
                ("masjid", "Aether-Node", 0.2112),
                ("layer", "Aether-Node", 0.3292),
                ("corners", "Aether-Node", 0.2424),
                ("heron", "Aether-Node", 0.2368),
                ("howell", "Aether-Node", 0.2122),
                ("pockets", "Aether-Node", 0.2838),
                ("florence", "Aether-Node", 0.1944),
                ("aerodrome", "Aether-Node", 0.2699),
                ("cohen", "Aether-Node", 0.1550),
                ("tangle", "Aether-Node", 0.3688),
                ("nebula", "Aether-Node", 0.1793),
                ("passageway", "Aether-Node", 0.2996),
                ("holes", "Aether-Node", 0.2461),
                ("cardiff", "Aether-Node", 0.1926),
                ("housed", "Aether-Node", 0.2449),
                ("traces", "Aether-Node", 0.3699),
                ("comb", "Aether-Node", 0.2609),
                ("clarence", "Aether-Node", 0.2248),
                ("surrounding", "Aether-Node", 0.2953),
                ("barak", "Aether-Node", 0.1977),
                ("surreal", "Aether-Node", 0.1535),
                ("bowman", "Aether-Node", 0.1851),
                ("astronomy", "Aether-Node", 0.3203),
                ("chests", "Aether-Node", 0.1928),
                ("outskirts", "Aether-Node", 0.2232),
                ("shape", "Aether-Node", 0.3029),
                ("existence", "Aether-Node", 0.2829),
                ("byrne", "Aether-Node", 0.1570),
                ("intersects", "Aether-Node", 0.2941),
                ("gunther", "Aether-Node", 0.1813),
                ("gaped", "Aether-Node", 0.1870),
                ("spaced", "Aether-Node", 0.3253),
                ("tunnel", "Aether-Node", 0.2567),
                ("diaz", "Aether-Node", 0.1429),
                ("thom", "Aether-Node", 0.2157),
                ("cummings", "Aether-Node", 0.1662),
                ("calcutta", "Aether-Node", 0.2218),
                ("situated", "Aether-Node", 0.3177),
                ("astronomers", "Aether-Node", 0.2787),
                ("ubiquitous", "Aether-Node", 0.3572),
                ("mellon", "Aether-Node", 0.2558),
                ("geometry", "Aether-Node", 0.3685),
                ("docking", "Aether-Node", 0.2593),
                ("frank", "Aether-Node", 0.2008),
                ("steiner", "Aether-Node", 0.2545),
                ("spin", "Aether-Node", 0.3484),
                ("consciousness", "Aether-Node", 0.2668),
                ("quarters", "Aether-Node", 0.2918),
                ("consisting", "Aether-Node", 0.3225),
                ("bangs", "Aether-Node", 0.2218),
                ("resides", "Aether-Node", 0.2533),
                ("shapes", "Aether-Node", 0.3672),
                ("connected", "Aether-Node", 0.3106),
                ("bose", "Aether-Node", 0.2330),
                ("langley", "Aether-Node", 0.2797),
                ("waterford", "Aether-Node", 0.1900),
                ("physicist", "Aether-Node", 0.3402),
                ("containment", "Aether-Node", 0.3650),
                ("semiconductor", "Aether-Node", 0.2793),
                ("belong", "Aether-Node", 0.2288),
                ("realities", "Aether-Node", 0.2391),
                ("francoise", "Aether-Node", 0.1886),
                ("nets", "Aether-Node", 0.3079),
                ("ponder", "Aether-Node", 0.2895),
                ("edge", "Aether-Node", 0.2784),
                ("vale", "Aether-Node", 0.1925),
                ("gong", "Aether-Node", 0.2688),
                ("dixon", "Aether-Node", 0.2277),
                ("cardinal", "Aether-Node", 0.2164),
                ("complexes", "Aether-Node", 0.2725),
                ("doors", "Aether-Node", 0.2654),
                ("clusters", "Aether-Node", 0.4379),
                ("tunnels", "Aether-Node", 0.2446),
                ("mansions", "Aether-Node", 0.1704),
                ("establishments", "Aether-Node", 0.2558),
                ("chen", "Aether-Node", 0.2570),
                ("ledge", "Aether-Node", 0.2411),
                ("munster", "Aether-Node", 0.1372),
                ("surrounds", "Aether-Node", 0.1974),
                ("adjoining", "Aether-Node", 0.2184),
                ("layers", "Aether-Node", 0.3429),
                ("brink", "Aether-Node", 0.1766),
                ("inclusion", "Aether-Node", 0.3036),
                ("networks", "Aether-Node", 0.4564),
                ("discrete", "Aether-Node", 0.3740),
                ("anhalt", "Aether-Node", 0.1609),
                ("imam", "Aether-Node", 0.2531),
                ("cessna", "Aether-Node", 0.2855),
                ("meeting", "Aether-Node", 0.2998),
                ("andre", "Aether-Node", 0.2218),
                ("bernstein", "Aether-Node", 0.2547),
                ("constructed", "Aether-Node", 0.3569),
                ("intersection", "Aether-Node", 0.3271),
                ("burnett", "Aether-Node", 0.2297),
                ("flanked", "Aether-Node", 0.2967),
                ("diagonal", "Aether-Node", 0.2862),
                ("residential", "Aether-Node", 0.2472),
                ("telescope", "Aether-Node", 0.2579),
                ("closure", "Aether-Node", 0.1932),
                ("belonging", "Aether-Node", 0.2219),
                ("territorial", "Aether-Node", 0.2662),
                ("electron", "Aether-Node", 0.2941),
                ("peered", "Aether-Node", 0.2923),
                ("soup", "Aether-Node", 0.2050),
                ("unions", "Aether-Node", 0.2236),
                ("electrons", "Aether-Node", 0.2592),
                ("alley", "Aether-Node", 0.1877),
                ("bedroom", "Aether-Node", 0.2126),
                ("maps", "Aether-Node", 0.3837),
                ("inhabit", "Aether-Node", 0.2409),
                ("stern", "Aether-Node", 0.1747),
                ("ripley", "Aether-Node", 0.1606),
                ("dwelling", "Aether-Node", 0.2232),
                ("separates", "Aether-Node", 0.2044),
                ("continuous", "Aether-Node", 0.2378),
                ("astronomer", "Aether-Node", 0.2714),
                ("telescopes", "Aether-Node", 0.2223),
                ("encompassing", "Aether-Node", 0.3747),
                ("house", "Aether-Node", 0.2685),
                ("visits", "Aether-Node", 0.2698),
                ("waldo", "Aether-Node", 0.2150),
                ("cage", "Aether-Node", 0.2149),
                ("fortifications", "Aether-Node", 0.1554),
                ("tentacles", "Aether-Node", 0.2210),
                ("murmur", "Aether-Node", 0.2456),
                ("depths", "Aether-Node", 0.2123),
                ("bavaria", "Aether-Node", 0.1422),
                ("fellows", "Aether-Node", 0.2542),
                ("plank", "Aether-Node", 0.2734),
                ("abstract", "Aether-Node", 0.2879),
                ("heaven", "Aether-Node", 0.2155),
                ("characterization", "Aether-Node", 0.2691),
                ("neighbours", "Aether-Node", 0.2216),
                ("storey", "Aether-Node", 0.2770),
                ("meetings", "Aether-Node", 0.2904),
                ("matter", "Aether-Node", 0.3301),
                ("parrot", "Aether-Node", 0.2088),
                ("hollow", "Aether-Node", 0.1847),
                ("mesh", "Aether-Node", 0.3611),
                ("networking", "Aether-Node", 0.4356),
                ("shaped", "Aether-Node", 0.2766),
                ("hallway", "Aether-Node", 0.2214),
                ("barton", "Aether-Node", 0.1623),
                ("adriatic", "Aether-Node", 0.2098),
                ("atom", "Aether-Node", 0.2781),
                ("segment", "Aether-Node", 0.3433),
                ("roche", "Aether-Node", 0.1237),
                ("biscuits", "Aether-Node", 0.1638),
                ("denny", "Aether-Node", 0.2239),
                ("devon", "Aether-Node", 0.1546),
                ("intersecting", "Aether-Node", 0.3241),
                ("irrational", "Aether-Node", 0.2350),
                ("berth", "Aether-Node", 0.1911),
                ("barrier", "Aether-Node", 0.2601),
                ("horizon", "Aether-Node", 0.2792),
                ("representation", "Aether-Node", 0.3980),
                ("etched", "Aether-Node", 0.2727),
                ("roaming", "Aether-Node", 0.2964),
                ("teller", "Aether-Node", 0.2387),
                ("intersections", "Aether-Node", 0.2878),
                ("loops", "Aether-Node", 0.4623),
                ("rectangular", "Aether-Node", 0.3147),
                ("cages", "Aether-Node", 0.2444),
                ("lobes", "Aether-Node", 0.2064),
                ("photon", "Aether-Node", 0.3068),
                ("bedrooms", "Aether-Node", 0.1842),
                ("bits", "Aether-Node", 0.4196),
                ("brows", "Aether-Node", 0.3576),
                ("barnsley", "Aether-Node", 0.1830),
                ("neil", "Aether-Node", 0.2233),
                ("augmented", "Aether-Node", 0.3778),
                ("intersect", "Aether-Node", 0.3677),
                ("bologna", "Aether-Node", 0.1974),
                ("cortex", "Aether-Node", 0.3461),
                ("gaps", "Aether-Node", 0.2916),
                ("neighbouring", "Aether-Node", 0.2723),
                ("menon", "Aether-Node", 0.2265),
                ("inception", "Aether-Node", 0.2435),
                ("vacancy", "Aether-Node", 0.3086),
                ("rational", "Aether-Node", 0.2551),
                ("hole", "Aether-Node", 0.2235),
                ("bays", "Aether-Node", 0.2803),
                ("antwerp", "Aether-Node", 0.1417),
                ("della", "Aether-Node", 0.2363),
                ("ethernet", "Aether-Node", 0.3190),
                ("galaxy", "Aether-Node", 0.2905),
                ("pact", "Aether-Node", 0.1949),
                ("quadrant", "Aether-Node", 0.2931),
                ("vortex", "Aether-Node", 0.2363),
                ("owls", "Aether-Node", 0.1839),
                ("segments", "Aether-Node", 0.3473),
                ("homes", "Aether-Node", 0.2265),
                ("avenues", "Aether-Node", 0.2284),
                ("cluster", "Aether-Node", 0.4482),
                ("counter", "Aether-Node", 0.3629),
                ("interred", "Aether-Node", 0.1724),
                ("hunan", "Aether-Node", 0.1565),
                ("curtains", "Aether-Node", 0.1704),
                ("vertices", "Aether-Node", 0.3005),
                ("interface", "Aether-Node", 0.3916),
                ("nell", "Aether-Node", 0.2047),
                ("centered", "Aether-Node", 0.2490),
                ("halls", "Aether-Node", 0.1498),
                ("bangalore", "Aether-Node", 0.2186),
                ("continuity", "Aether-Node", 0.1877),
                ("hannover", "Aether-Node", 0.1631),
                ("belonged", "Aether-Node", 0.2026),
                ("museum", "Aether-Node", 0.2221),
                ("inward", "Aether-Node", 0.2070),
                ("knox", "Aether-Node", 0.2087),
                ("hostel", "Aether-Node", 0.1716),
                ("alma", "Aether-Node", 0.1614),
                ("indoor", "Aether-Node", 0.2382),
                ("organizer", "Aether-Node", 0.3428),
                ("pits", "Aether-Node", 0.1472),
                ("atoms", "Aether-Node", 0.2347),
                ("pagoda", "Aether-Node", 0.2385),
                ("baba", "Aether-Node", 0.2160),
                ("path", "Aether-Node", 0.2492),
                ("rings", "Aether-Node", 0.2644),
                ("operator", "Aether-Node", 0.3506),
                ("franciscan", "Aether-Node", 0.1498),
                ("layered", "Aether-Node", 0.3283),
                ("dimensional", "Aether-Node", 0.3244),
                ("bank", "Aether-Node", 0.2789),
                ("gladstone", "Aether-Node", 0.1392),
                ("bengal", "Aether-Node", 0.2017),
                ("synagogue", "Aether-Node", 0.1835),
                ("groove", "Aether-Node", 0.2429),
                ("bristol", "Aether-Node", 0.2047),
                ("luftwaffe", "Aether-Node", 0.2344),
                ("inhabited", "Aether-Node", 0.2525),
                ("corner", "Aether-Node", 0.2118),
                ("pigeons", "Aether-Node", 0.1700),
                ("mane", "Aether-Node", 0.2389),
                ("broadband", "Aether-Node", 0.3177),
                ("neptune", "Aether-Node", 0.1803),
                ("cavern", "Aether-Node", 0.2172),
                ("through", "Aether-Node", 0.2445),
                ("underneath", "Aether-Node", 0.2391),
                ("sirius", "Aether-Node", 0.1951),
                ("attractions", "Aether-Node", 0.1432),
                ("bowls", "Aether-Node", 0.2403),
                ("slit", "Aether-Node", 0.2558),
                ("connacht", "Aether-Node", 0.1351),
                ("boundaries", "Aether-Node", 0.3016),
                ("edged", "Aether-Node", 0.2648),
                ("encompass", "Aether-Node", 0.1903),
                ("fanny", "Aether-Node", 0.1881),
                ("labyrinth", "Aether-Node", 0.2215),
                ("travers", "Aether-Node", 0.4255),
                ("ring", "Aether-Node", 0.2617),
                ("clifford", "Aether-Node", 0.2778),
                ("town", "Aether-Node", 0.2492),
    ]

    amplified_triplets = raw_triplets * 5
    
    train_examples = []
    for t in amplified_triplets:
        train_examples.append(InputExample(texts=[t[0], t[1]], label=float(t[2])))
        
    print(f"-> Corpus built with {len(train_examples)} geometric instructions.")
    return train_examples

def execute_omni_paving():
    print("=== JIT_ATL: PHASE 14 - ABSOLUTE OMNI CAGE ===\n")
    
    model_name = 'all-MiniLM-L6-v2'
    print(f"Loading Model A ({model_name})...")
    model = SentenceTransformer(model_name)
    
    train_examples = build_omni_corpus()
    train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)
    train_loss = losses.CosineSimilarityLoss(model)
    
    print("\n-> Initiating Omni-Scaffold Fine-Tuning (Tracking Compute Matrix Expansion)...")
    
    start_time = time.time()
    model.fit(
        train_objectives=[(train_dataloader, train_loss)],
        epochs=10,
        warmup_steps=10,
        show_progress_bar=True
    )
    end_time = time.time()
    execution_time = end_time - start_time
    
    output_path = "./JIT_ATL/Model_B_Absolute"
    os.makedirs(output_path, exist_ok=True)
    model.save(output_path)
    
    print(f"\n-> SUCCESS: Model B (Omni-Scaffold) saved to {output_path}")
    print(f"-> Omni-Scaffold Training Duration: {execution_time:.2f} seconds")

if __name__ == "__main__":
    execute_omni_paving()
